### PR TITLE
Consistency and link to client config

### PR DESCRIPTION
**Pull request by fliiiix**
Idk maybe it would be possible to link it relativ but I didn't found out how it would work.

### CODE REVIEW

**Comment by jelmer** [comment]
Please don't use absolute links - it breaks offline access to the docs. You may want to create references to client.html instead to link to the local file?

**Comment by fliiiix** [comment]
fair point - I will try

**Comment by fliiiix** [comment]
This should work.

**Comment by jelmer** [comment]
This is still using an absolute path; on my system it links to /configuration/client (i.e. on the filesystem root)

**Comment by fliiiix** [comment]
It's absolute to the root of your webserver. Which worked for the render thing I tried. How do you use it?

Can you tell me with what you are rendering the rst files?

**Comment by jelmer** [comment]
That assumes the docs are located at the root, it i.e. breaks when I access a local copy of the docs.

**Comment by fliiiix** [comment]
How about this?

**Pull request merged**
