### PR TITLE
Add reference to Easypanel

### PR DESCRIPTION
**Pull request by Supernova3339**
Add a reference to the Easypanel template

## What changes does this Pull Request introduce?

This adds a reference to the Easypanel template to make deployment easier for Isso users.

## Why is this necessary?

This makes deployment easier, and uses all current configuration values.

### CODE REVIEW

**Comment by ix5** [comment]
Hi, thank you for your contribution. Since many people might not be familiar with this easypanel technology, would you mind explaining what it is?

Have you actually verified that the deployment with easypanel works?

In any case, please move this section to either the [community](https://github.com/posativ/isso/blob/6e23ab6f119560c5745760ee0e91276ec43b6c75/docs/community.rst) or [deployment](https://github.com/posativ/isso/blob/6e23ab6f119560c5745760ee0e91276ec43b6c75/docs/docs/reference/deployment.rst) docs section.

**Comment by Supernova3339** [comment]
> Hi, thank you for your contribution. Since many people might not be familiar with this easypanel technology, would you mind explaining what it is?
> 
> Have you actually verified that the deployment with easypanel works?
> 
> In any case, please move this section to either the [community](https://github.com/posativ/isso/blob/6e23ab6f119560c5745760ee0e91276ec43b6c75/docs/community.rst) or [deployment](https://github.com/posativ/isso/blob/6e23ab6f119560c5745760ee0e91276ec43b6c75/docs/docs/reference/deployment.rst) docs section.

Hi @ix5 :wave: 

I can confirm it works, as I am the template creator. Easypanel is a docker based solution, which uses FILE mounts to edit isso's configuration. I've included everything there that should be included. If you have any questions, please let me know.

**Comment by ix5** [comment]
> Hi @ix5
> 
> I can confirm it works, as I am the template creator. Easypanel is a docker based solution, which uses FILE mounts to edit isso's configuration. I've included everything there that should be included. If you have any questions, please let me know.

Then please include that information you just told me in addition to the link in the docs section so that others can also benefit from it.

**Comment by Supernova3339** [comment]
where would you like me to include this? I am slightly confused.

**Comment by ix5** [comment]
Please add the "explanation" of what easypanel is supposed to be in the same section that you add the link to.

As explained above:

> In any case, please move this section [meaning the reference to easypanel] to either the [community](https://github.com/posativ/isso/blob/6e23ab6f119560c5745760ee0e91276ec43b6c75/docs/community.rst) or [deployment](https://github.com/posativ/isso/blob/6e23ab6f119560c5745760ee0e91276ec43b6c75/docs/docs/reference/deployment.rst) docs section.

**Comment by ix5** [comment]
@Supernova3339 please update as requested, closing this otherwise.

**Comment by Supernova3339** [comment]
I don't know how to do that

**Comment by ix5** [comment]
@Supernova3339 I've updated your PR and moved the reference to Easypanel to the `community` section of the docs, as has been explained to you numerous times now.

You, @Supernova3339, already know what Easypanel is, but you cannot assume that everyone reading the `README` of Isso will already be familiar with what Easypanel is. That is why you should at least explain _in the docs_ that it is a "Server Control Panel" that allows "1-click installs".

As for why we asked you to move the reference to the community section: The README should be a brief overview. We cannot add every conceivable link in there, or it'd become cluttered and confusing. That's why the docs are a better place, especially since the [community section](https://github.com/posativ/isso/blob/d01d881479253d5b19fe178b6549a08b3ed48044/docs/community.rst?plain=1#L85-L93) already links to similar resources that integrate Isso with other systems.

Please try to research a bit more and put yourself in the maintainers' shoes next time, since this has cost me and jelmer unnecessary time over the months. Thank you nonetheless for your contribution and for making the effort to grow the Isso-friendly ecosystem!

**Comment by Supernova3339** [comment]
I'm really sorry, but I have never heard of a community section. Are you
referring to discussions? I am more then happy to assist in getting my PR
approved.

**Pull request merged**
