### PR TITLE
Be less aggresive when extending the DOM

### PR DESCRIPTION
**Pull request by xuhdev**
This should fix getnikola/nikola#1714. The show() and hide() functions are too aggresive and easy to cause confliction.

### CODE REVIEW

**Comment by xuhdev** [comment]
Is there any possibility to get this merged? Thanks!

**Comment by posativ** [comment]
Probably not, that's just a workaround for jQuery. I am currently working on a better patch that does not extend global objects.

**Comment by posativ** [comment]
@xuhdev can you please try

```diff
diff --git a/isso/js/app/dom.js b/isso/js/app/dom.js
index 6338d1f..fc2de7b 100644
--- a/isso/js/app/dom.js
+++ b/isso/js/app/dom.js
@@ -2,31 +2,35 @@ define(function() {
 
     "use strict";
 
-    window.Element.prototype.replace = function(el) {
+    function Element(el) {
+        this.element = el;
+    }
+
+    Element.prototype.replace = function(el) {
         var element = DOM.htmlify(el);
         this.parentNode.replaceChild(element, this);
         return element;
     };
 
-    window.Element.prototype.prepend = function(el) {
+    Element.prototype.prepend = function(el) {
         var element = DOM.htmlify(el);
         this.insertBefore(element, this.firstChild);
         return element;
     };
 
-    window.Element.prototype.append = function(el) {
+    Element.prototype.append = function(el) {
         var element = DOM.htmlify(el);
         this.appendChild(element);
         return element;
     };
 
-    window.Element.prototype.insertAfter = function(el) {
+    Element.prototype.insertAfter = function(el) {
         var element = DOM.htmlify(el);
         this.parentNode.insertBefore(element, this.nextSibling);
         return element;
     };
 
-    window.Element.prototype.on = function(type, listener, prevent) {
+    Element.prototype.on = function(type, listener, prevent) {
         /*
         Shortcut for `Element.addEventListener`, prevents default event
         by default, set :param prevents: to `false` to change that behavior.
@@ -39,7 +43,7 @@ define(function() {
         });
     };
 
-    window.Element.prototype.toggle = function(type, a, b) {
+    Element.prototype.toggle = function(type, a, b) {
         /*
         Toggle between two internal states on event :param type: e.g. to
         cycle form visibility. Callback :param a: is called on first event,
@@ -77,25 +81,22 @@ define(function() {
         });
     };
 
-    window.Element.prototype.detach = function() {
-        /*
-        Detach an element from the DOM and return it.
-         */
-
+    Element.prototype.detach = function() {
+        // Detach an element from the DOM and return it.
         this.parentNode.removeChild(this);
         return this;
     };
 
-    window.Element.prototype.remove = function() {
+    Element.prototype.remove = function() {
         // Mimimi, I am IE and I am so retarded, mimimi.
         this.parentNode.removeChild(this);
     };
 
-    window.Element.prototype.show = function() {
+    Element.prototype.show = function() {
         this.style.display = "block";
     };
 
-    window.Element.prototype.hide = function() {
+    Element.prototype.hide = function() {
         this.style.display = "none";
     };
 
@@ -122,23 +123,29 @@ define(function() {
         }
 
         if (elements.length === 1 && single) {
-            return elements[0];
+            return new Element(elements[0]);
         }
 
-        return elements;
+        return elements.map(function(el) {
+            return new Element(el);
+        });
     };
 
-    DOM.htmlify = function(html) {
+    DOM.htmlify = function(el) {
         /*
         Convert :param html: into an Element (if not already).
-         */
+        */
+
+        if (el instanceof  Element) {
+            return el;
+        }
 
-        if (html instanceof window.Element) {
-            return html;
+        if (el instanceof window.Element) {
+            return new Element(el);
         }
 
         var wrapper = DOM.new("div");
-        wrapper.innerHTML = html;
+        wrapper.innerHTML = el;
         return wrapper.firstChild;
     };
 
@@ -152,7 +159,7 @@ define(function() {
                 div = DOM.new("textarea.foo", "...")
          */
 
-        var el = document.createElement(tag.split(".")[0]);
+        var el = new Element(document.createElement(tag.split(".")[0]));
         tag.split(".").slice(1).forEach(function(val) { el.classList.add(val); });
 
         if (["A", "LINK"].indexOf(el.nodeName) > -1) {

```

**Comment by xuhdev** [comment]
@posativ I saw you've posted a patch here but removed. Do you still expect the patch to work?

**Comment by posativ** [comment]
The patch didn't work, the element needs to proxy all `window.Element` methods.

**Comment by pozitron57** [comment]
Thanks @xuhdev, it helped me with [#203](https://github.com/posativ/isso/issues/203) as @posativ adviced.

**Comment by posativ** [comment]
Fixed in 0.10.

**Pull request closed without merging**
