### PR TITLE
Upgrade from pyflakes to flake8

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by blatinier** [comment]
Could you rebase on posativ/master to merge please?

**Comment by jelmer** [comment]
This whitelists certain errors, disabling many of the other errors we check for at the moment. Can you blacklist problematic ones instead?

On 1 February 2018 07:00:52 GMT+11:00, "Benoît Latinier" <notifications@github.com> wrote:
>Could you rebase on posativ/master to merge please?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/posativ/isso/pull/384#issuecomment-362052928

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
https://www.jelmer.uk/

**Comment by cclauss** [comment]
The first flake8 run covers those five issues that can halt the runtime.  The second flake8 run shows us which ”style” tests are failing without failing the overall build.  The results look like: https://travis-ci.org/posativ/isso/jobs/335629233#L682-L705  Do we really want a blacklist that is 23 tests long?  Do we want to run autopep8 or yapf on the codebase to auto-eliminate most of these style errors before locking down the blacklist?  The other alternative is to fix all issues and the have zero tolerance for any flake8 issues.  This is how cpython and Django work.

**Comment by blatinier** [comment]
I prefer the blacklist too. Most errors in the travis are easily fixable styling stuff. The complexity issues might be trickier and blacklisted to begin with however I prefer to aim at a zero tolerance policy.

**Comment by blatinier** [comment]
Since #386 is merge, this can be closed.

**Pull request closed without merging**
