### PR TITLE
use author names in gravatars

### PR DESCRIPTION
**Pull request by rr-**
We're using gravatars. Most of our users do not provide e-mails. With the current implementation, different people look the same (they all use default icon) and as such, the avatars aren't very useful.

The proposed change makes gravatars fall back to authors' nicknames when they didn't provide an e-mail. That way, if someone leaves multiple comments under the same nickname, they'll have the same gravatar, but they'll still be different from other users who use different nicknames.

### CODE REVIEW

**Comment by jelmer** [comment]
This is a bit of a hack; it sets the email variable to something that is not an email address, and makes a request to gravatar that it knows is not going to get it a proper gravatar image.

**Comment by rr-** [comment]
I can put it behind a configuration variable if you want me to.

**Comment by jelmer** [comment]
On Tue, Nov 13, 2018 at 07:40:15AM -0800, Marcin Kurczewski wrote:
> I can put it behind a configuration variable if you want me to.
Sorry, I should have explained better. It seems suboptimal
to send the full names of commenters to gravatar when we're not
going to get actual photos back but just generated avatars.

isso already has a mechanism for generating unique avatars based on
hashes, which we could use here, and which wouldn't leak commenter
names.

Jelmer

**Comment by rr-** [comment]
>isso already has a mechanism for generating unique avatars based on
hashes, which we could use here, and which wouldn't leak commenter
names.

That's interesting, could you point me to it? Thanks

**Comment by jelmer** [comment]
Isso uses the identicon library. Search the repository for that string to see how it is used.

**Comment by jelmer** [comment]
ping?

**Comment by rr-** [comment]
I forgot about this PR. Now that I looked at the code, this will make the site appear weird: users with e-mail but no gravatar will have one kind of default identicon, while users with no e-mail will have another kind.

**Comment by jelmer** [comment]
Ah, fair enough. This is not unreasonable since it would only happen for sites that already have gravatar enabled anyway.

**Pull request merged**
