### PR TITLE
Adding a [server] proxy-fix-enable-x-prefix configuration option

### PR DESCRIPTION
**Pull request by Lucas-C**
...to take into consideration the `X-Forwarded-Prefix` HTTP header

### CODE REVIEW

**Comment by Lucas-C** [comment]
This is needed for `werkzeug.wsgi.get_current_url` called in `isso/views/comments.py` to work properly when isso is hosted under a sub-path

**Comment by hamoid** [comment]
What happens without this? Asking because my isso is not working (not sending static files)

**Comment by Lucas-C** [comment]
When visiting `/isso/admin` there wasn't any image displayed.
With this fix, the stylesheets are correctly loaded and isso logo can be seen.

**Comment by Lucas-C** [comment]
I rebased this PR. It should be ready to merge

**Comment by Lucas-C** [comment]
Is this PR ready to be merged ? :)

**Comment by jelmer** [comment]
On Mon, Apr 20, 2020 at 10:10:24PM -0700, Lucas Cimon wrote:
> Is this PR ready to be merged ? :)

Could we just always set x_for=1 ?

Context for other reading along: https://werkzeug.palletsprojects.com/en/1.0.x/middleware/proxy_fix/

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by Lucas-C** [comment]
Sure !
At first I thought introducing a new configuration option would allow for more control, but really I do not see how always setting `x_for=1` would introduce any regression.

**Comment by Lucas-C** [comment]
PR updated !

**Comment by Lucas-C** [comment]
Thanks for merging this :)

**Pull request merged**
