### PR TITLE
Ok is not OK. Fixes #347

### LINKED ISSUE #347: Isso Forces CORS Preflight but is unable to handle CORS Preflight requests
Hello!

I am attempting to use Isso in my project, but the way I am using it I have to communicate directly with the API built into Isso. I am currently running into an issue where if I attempt to add a comment using the `/new` api endpoint, the request either will return a `CSRF` error (if I omit the `Content-Type` header), or a 502 error (if I attempt to call it like I do normally).

The issue is that Isso does not respond to the CORS preflight request.

Normally, the workaround would be to preform a [Simple Request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Simple_requests) using an `XMLHttpRequest` but if the `Content-Type` header is omitted (instead of being `application/json`) so that the request is compliant with being a "Simple Request", Isso throws a [`CSRF` error](https://github.com/posativ/isso/blob/master/isso/views/comments.py#L72) since the `Content-Type` header is unset.

The way to fix this bug would be to respond properly to the CORS preflight request (by listening to an `OPTIONS` request being made to the `/new` api endpoint), or remove the requirement of adding the `Content-Type` header to allow it to be just a Simple Request.

I assume many have not run into this issue, as the CORS preflight request would not be sent if the user was on the same domain as the Isso server (since it would not be Cross Origin then).

Please let me know if you need any more information!

### PR DESCRIPTION
**Pull request by Konzertheld**

### CODE REVIEW

**Comment by Konzertheld** [comment]
In Python 2 on isso 0.12.2, that is.

**Comment by jelmer** [comment]
I've only briefly glanced at the issue; how does this fix the issue? Which code expects "OK" rather than "Ok" ?

**Comment by Konzertheld** [comment]
I just came across that issue (and the related ones) because I had CORS issues myself, seeing the preflight checks fail as their response was not "200 OK" - that's what I saw in the browser console. So I dug around in the code a little bit at the places discussed in the ticket and noticed the case was not correct. Changed it to OK and my problems went away. I never investigated the rest of the CORS handling.

**Comment by jelmer** [comment]
I'm hesitant about merging this without understanding how it fixes things - it seems wrong for other software to rely on specific capitalization.

**Comment by Konzertheld** [comment]
It's not completely random to use the capitalization - it's how it is defined in the HTTP protocol: https://tools.ietf.org/html/rfc2616#section-10.2.1

**Comment by jelmer** [comment]
On Sun, Oct 11, 2020 at 05:17:34PM -0700, Christian wrote:
> It's not completely random to use the capitalization - it's how it is defined in the HTTP protocol: https://tools.ietf.org/html/rfc2616#section-10.2.1
Yes, but the RFC also explicitly says that the reason phrase is for
human consumption and can be changed:

https://tools.ietf.org/html/rfc2616#section-6.1.1

"The reason phrases listed here are only recommendations -- they MAY
be replaced by local equivalents without affecting the protocol."

So whatever is expecting to see "OK" here with that specific
capitalization is violating the spec.

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by blatinier** [comment]
I agree on this with @jelmer It's not meant to be used by computers.
However I can guess how a poorly designed system could rely on this and it doesn't hurt to merge it anyway…

**Pull request merged**
