### PR TITLE
api: add /feed API to get an Atom feed for an URI

### LINKED ISSUE #81: RSS feed
Provide per-thread RSS (and maybe even all-comment) feeds for users that are interested in (any) follow-ups.

### PR DESCRIPTION
**Pull request by vincentbernat**
We need absolute URL at some places. We assume the first host
configured is the base of the URI we have.

Fix #81.

This is mostly a "RFC". Notably, tests are missing.

### CODE REVIEW

**Comment by vincentbernat** [comment]
Tests have been added. Caching should work properly and the client side too.

The only problem I see is the use of the first host defined in `[general]`. Maybe I should add an `[rss]` section instead an add a `base` parameter here instead?

**Comment by blatinier** [comment]
Just like you suggested, adding a section `[rss]` in the conf for the host & limit seems like a good way to fix my comments too.
Anyway thanks for you efforts, here and on other issues, I'll try to take some time to review, test and merge all that :)

**Comment by vincentbernat** [comment]
I've added a commit to include some configuration on both server-side and client-side.

**Comment by vincentbernat** [comment]
Forgot to include HTML rendering. I've pushed another commit for that.

**Pull request merged**
