### PR TITLE
Adding support for ISSO_CORS_ORIGIN env variable to allow defining wildcard CORS origins

### PR DESCRIPTION
**Pull request by Lucas-C**

### CODE REVIEW

**Comment by blatinier** [comment]
Could you document this env variable with a little example in the documentation?

**Comment by blatinier** [comment]
I merge this and create a documentation issue #407.

**Comment by ix5** [comment]
@Lucas-C it seems this feature is not working properly, see https://github.com/posativ/isso/issues/720

Do you feel like submitting a fix?

**Comment by Lucas-C** [comment]
Thanks for the ping @ix5 !
I'll have a look at it asap.

**Pull request merged**
