### PR TITLE
Verify the from email address is set to a valid value

### PR DESCRIPTION
**Pull request by MorrisJobke**
* checks if the `from` value is properly set
* tries to set a name if only the email address is given and checks there if the email address at least contains an `@` and no `space`
* includes some tests

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@posativ Is there no travis running here? I ran tox locally, but not for all versions.

@noqqe Maybe this is also the reason why your email config doesn't work. Just check if you either use `abc <abc@example.org>` or `abc@example.org`. 😉

**Comment by skorokithakis** [comment]
I'm afraid this pull request is misquided, as a space is a valid character in an email address.

**Comment by MorrisJobke** [comment]
> I'm afraid this pull request is misquided, as a space is a valid character in an email address.

Really? Is it then encoded like `%20`?

**Comment by skorokithakis** [comment]
No, it's enclosed in quotes, like this: valid."email address@"@example.com.

Even this is valid:

"very.(),:;<>[]\".VERY.\"very@\\ \"very\".unusual"@strange.example.com

More info: https://en.wikipedia.org/wiki/Email_address

**Comment by jelmer** [comment]
Could you perhaps simplify this to just print a warning if fromaddr is empty but parseaddr() on it fails? That should be enough of a hint to the user and is still better than silently falling back to "Ich schrei sonst!"

**Comment by jelmer** [comment]
Closing this out for now, since it's stalled and not ready to be merged. Please reopen if there are updates.

**Pull request closed without merging**
