### PR TITLE
tests(comments): use the new Werkzeug API to delete cookies

### PR DESCRIPTION
**Pull request by RaitoBezarius**
Since 2.4 [1], Werkzeug deprecated the old `server_name`-based API, the new way to delete cookies based on server name is to use `domain` kwarg.

This broke NixOS testing of `isso` with our newer dependencies [2].

[1]: https://werkzeug.palletsprojects.com/en/2.3.x/test/#werkzeug.test.Client.delete_cookie
[2]: https://github.com/NixOS/nixpkgs/issues/264081

## Checklist
- [x] All new and existing **tests are passing**
- [ ] (If adding features:) I have added tests to cover my changes
- [ ] (If docs changes needed:) I have updated the **documentation** accordingly.
- [ ] I have added an entry to `CHANGES.rst` because this is a user-facing change or an important bugfix
- [x] I have written **proper commit message(s)**
      

## What changes does this Pull Request introduce?

Use of non-deprecated API `Client.delete_cookie` in the tests.

## Why is this necessary?

Tests are broken with newer dependencies of Werkzeug, https://github.com/NixOS/nixpkgs/pull/264338 fixes it, https://github.com/NixOS/nixpkgs/issues/264081 reports it.

### CODE REVIEW

**Comment by jelmer** [comment]
We should drop 3.7 first though (which seems reasonable to me), so we can keep the CI green.

**Comment by RaitoBezarius** [comment]
> We should drop 3.7 first though (which seems reasonable to me), so we can keep the CI green.

Would you like me to do it in this PR or in another PR or would you prefer to do it and then I rebase?

**Comment by jelmer** [comment]
Please create a separate PR

**Comment by ix5** [comment]
While you're at it, please also bump the minimum required version of werkzeug to 2.3.0 (see [changelog](https://werkzeug.palletsprojects.com/en/3.0.x/changes/#version-2-3-0))

> The first positional `server_name` parameter to `set_cookie` and `delete_cookie` is deprecated. Use the `domain` parameter instead.

**Pull request merged**
