### PR TITLE
Add a github action

### PR DESCRIPTION
**Pull request by jelmer**
Add a github action.

### CODE REVIEW

**Comment by ix5** [comment]
Take a look at https://github.com/posativ/isso/pull/689 for some inspiration to broaden testing.
CircleCI isn't the way to go though as you have to be logged in to view results.

**Comment by jelmer** [comment]
@posativ any chance you can enable GitHub actions for the isso repo?

**Comment by posativ** [comment]
Not sure what do enable here specifically:

image

I guess it should work after this has been merged?

**Comment by jelmer** [comment]
Ah, thanks for checking - I'll give merging a go and see what happens.

**Pull request merged**
