### PR TITLE
Reply notification

### PR DESCRIPTION
**Pull request by tsileo**
Hi,

I love Isso, but the only thing that prevent me to drop Disqus for Isso is the ability for commenters to receive an email notification of reply.

I get a working version with this feature (I use it in production on my blog: http://thomassileo.com), it still need some improvement, I just open the pull request to open the discussion.

What do you think about this feature ?

I added a field in the comment table, is this something that will prevent you to merge this feature ?

Let me know what you think about this,

Thanks!

### CODE REVIEW

**Comment by noqqe** [comment]
any news?

**Comment by pozitron57** [comment]
:+1: for this feature!

**Comment by jacmoe** [comment]
It would be really great to have this feature because I have several places where I would like Isso to replace Disqus..

But my sites are not really something that my commenters are following like hawks, so they would probably never notice that they got a reply, let alone even remember that they visited my sites :P

This feature would be the one that actually made me ditch Disqus completely.

**Comment by dertuxmalwieder** [comment]
AFAIR other self-hosted comment systems have it, so you *could* already ditch Disqus...

**Comment by jacmoe** [comment]
> AFAIR other self-hosted comment systems have it, so you could already ditch Disqus...

So, *could* I .. let me see: what other self-hosted systems are there that are as good as Isso?  
I have found none.

**Comment by dertuxmalwieder** [comment]
Last time I checked, HashOver (2.0, not "final" yet) seemed to be pretty decent.

**Comment by jacmoe** [comment]
Hashover has a license that I don't agree with, and it seems a bit clunky. Especially the interface, which is important to me. But, yes: that is pretty close :)

**Comment by varod** [comment]
+1

**Comment by tofof** [comment]
Not clear why this isn't more urgently being integrated.

**Comment by dkbast** [comment]
Is there anything we could do to help the process? This feature is currently the only thing holding me back from making the transition to isso.

**Comment by blatinier** [comment]
Just to answer @dertuxmalwieder on his message on optout not being needed (yes it's more than 2 years ago :D) → optout links in emails are a legal obligation in France. I think France is not the only country requesting such a link. This PR should implement both double opt-in & optout to be completly ok I think.

**Comment by kaushalmodi** [comment]
Looking forward to this feature. While I can enable email notifications when people comment on my blog, I'd like people to optionally start/stop notifications when people reply to their comments.

**Comment by farmdawgnation** [comment]
What's the status of this? This has been open for awhile and still unmerged. I'm looking at Isso pretty seriously, but this is something that's missing imo.

**Comment by posativ** [comment]
There is no opt-out, which is a hard requirement before I can consider merging.

**Comment by zhangnew** [comment]
I think add a checkbox let user choose send email for his comment be replied or not is a good idea.

**Comment by goxofy** [comment]
Maybe someone cloud resolve the conficts with this branch？

**Comment by rawsh** [comment]
Bump. This is a super feature

**Comment by pellenilsson** [comment]
I [merged this to current master](https://github.com/pellenilsson/isso/tree/reply_notification) and implemented opt-out using a link in every mail sent. And I made some small additional improvements:

* Fix for a thread problem that popped up, see #395.
* Add the new column to database if needed (by simply adding the column in a `try` statement, maybe there is a nicer way).
* Include a link to the comment itself in the email (as was already done for the admin emails).

**Comment by pellenilsson** [comment]
There is one thing in this implementation that I'm not happy about, though. If you check the "Subscribe to email notification of replies" checkbox when making a *reply*, you will never get any notifications, since you can't really reply to a reply. I can see a number of solutions:

1. Don't show the checkbox at all when writing replies.
2. Checking the checkbox for a reply could mean that author gets notifications for all replies to the same parent comment that he/she replied to.
3. Even though the *Reply* buttons shown after each reply currently has the exact same effect as clicking *Reply* on the parent comment, it could still be arranged so that notifications are sent based on exactly which *Reply* button you pressed.

Any preferences on this?

**Comment by rawsh** [comment]
I feel like it should act the same as the parent comment. Thanks for update, testing now

**Comment by pellenilsson** [comment]
I agree with @rawsh that solution 2 is the most intuitive one. I updated my branch with this behavior.

**Comment by FiveYellowMice** [comment]
I think solution 3 provides the best user experience, though it doesn't seem it can be implemented cleanly with the current reply model.

**Comment by blatinier** [comment]
@pellenilsson I would very much appreciate your contribution for my own instance and thus consider merging it soon. This current PR is a bit too much outdated and requires some updates on the latest discussions.

**Comment by pellenilsson** [comment]
@vincentbernat @blatinier Working on it! I merged with master again (after the Gravatar and Preview additions), but there are some details left to fix. Will create a new PR after that.

**Comment by blatinier** [comment]
That's great news! Thanks for your work in advance

**Comment by jalcine** [comment]
Oh this is awesome!

**Comment by dertuxmalwieder** [comment]
It is!

**Comment by rawsh** [comment]
Thanks!

**Pull request merged**
