### PR TITLE
Feature/gravatar support

### PR DESCRIPTION
**Pull request by benjhess**
Adds optional gravatar support. See Issue: [141](https://github.com/posativ/isso/issues/141).

To enable this on the server set ini config:
`gravatar = true`

This will add field "gravatar_image" to the result of each comment. Uses a random gravatar image when no mail given for a comment :)

And on client side:
`<script data-isso="/isso"
        data-isso-avatar="false"
        data-isso-gravatar="true"
        ...
</script>`

### CODE REVIEW

**Comment by pascalw** [comment]
Great work! Would love to see this merged 👍

**Comment by hamoid** [comment]
This discussion might help understand why some people are against, and others in favor of using Gravatar: https://meta.stackexchange.com/questions/44717/is-gravatar-a-privacy-risk

**Comment by zhangnew** [comment]
Can I use this pr code in my forked repository ?

**Comment by fede91it** [comment]
Can we merge this?

**Pull request merged**
