### PR TITLE
js: templates: Remove invalid `role="meta"` from comment template

### PR DESCRIPTION
**Pull request by BBaoVanC**
## Checklist
- [ ] All new and existing **tests are passing**
- [ ] ~~(If adding features:) I have added tests to cover my changes~~
- [ ] ~~(If docs changes needed:) I have updated the **documentation** accordingly.~~
- [ ] ~~`I have added an entry to `CHANGES.rst` because this is a user-facing change or an important bugfix~~
- [x] I have written **proper commit message(s)**
      

## What changes does this Pull Request introduce?

This removes the `role="meta"` attribute from `div.isso-comment-header` in the `comment.js` template. Since this is the only element in the entire app that even sets the `role` attribute, I decided to remove it entirely rather than try and pick the correct ARIA `role`.

See also:

- https://web.dev/aria-roles/?utm_source=lighthouse&utm_medium=ci
- https://www.w3.org/TR/wai-aria-1.1/#role_definitions

## Why is this necessary?

Since `meta` is not a valid option for the ARIA `role` attribute, it throws a warning from Google Chrome Lighthouse. 

It first appeared in https://github.com/posativ/isso/commit/66ade6df1404312065e4bb4bfa8bebe0bf3c6027#diff-df9126d15312dce83218b5d92b1463a8e6d8f8eea0c556ec7dae8d2526690a45R6, but I can't tell if it was valid at the time. Anyways, it's not a valid role today so it can be removed.

Also see the [results from Lighthouse CI](https://lhci.bbaovanc.com/app/projects/bbaovanc.com/compare/738f53b19d64?baseUrl=https%3A%2F%2Flocalhost%2Fblog%2Fedited-in-middle-of-message-discord%2F&compareUrl=https%3A%2F%2Flocalhost%2Fblog%2Fedited-in-middle-of-message-discord%2F), which I run on my website:

image

image

### CODE REVIEW

**Comment by BBaoVanC** [comment]
Also, it would be nice if the GitHub Actions workflow had a step for the E2E and unit tests which would upload the changed snapshot, like it does for the screenshots ("Update screenshot hashes (if mismatched)" and "Archive and upload updated screenshots and hashes", but for E2E and unit tests). There aren't docs yet for the E2E tests and I wasn't able to figure out how to update them.

**Comment by ix5** [comment]
> Also, it would be nice if the GitHub Actions workflow had a step for the E2E and unit tests which would upload the changed snapshot, like it does for the screenshots ("Update screenshot hashes (if mismatched)" and "Archive and upload updated screenshots and hashes", but for E2E and unit tests).

That's a good idea, would you mind submitting a PR for that?

> There aren't docs yet for the E2E tests and I wasn't able to figure out how to update them.

Updating snapshots should be documented here: [Testing the Client: Updating Snapshots](https://isso-comments.de/docs/technical-docs/testing-client/#updating-snapshots). But maybe this is a bit hard to find.

---

Would you mind updating the snapshot so it passes the docker e2e tests? It's currently failing (I only looked at CI so far).

**Comment by BBaoVanC** [comment]
> Updating snapshots should be documented here: [Testing the Client: Updating Snapshots](https://isso-comments.de/docs/technical-docs/testing-client/#updating-snapshots). But maybe this is a bit hard to find.
> 
> Would you mind updating the snapshot so it passes the docker e2e tests? It's currently failing (I only looked at CI so far).

That link shows how to update the regular snapshots, which I already did. It looks like there must be some other snapshots that are used in the integration tests, which are the ones that are failing on Docker.

image

**Comment by ix5** [comment]
@BBaoVanC 
https://github.com/posativ/isso/commit/4f14b60367f057cfd314c3fc6c771c41a95acdcc

**Comment by BBaoVanC** [comment]
> @BBaoVanC [4f14b60](https://github.com/posativ/isso/commit/4f14b60367f057cfd314c3fc6c771c41a95acdcc)

I ran the server, and then tried using `npm run test-integration -- -u`, but I got an error:

```
● Validation Error:

  Preset jest-puppeteer not found.

  Configuration Documentation:
  https://jestjs.io/docs/configuration
```

After looking at the Dockerfile, I found that I needed to run `npm i --no-save jest-puppeteer`, which worked.

**Comment by ix5** [comment]
@BBaoVanC 
See https://github.com/posativ/isso/blob/4f14b60367f057cfd314c3fc6c771c41a95acdcc/docs/docs/technical-docs/testing-client.rst#end-to-end-integration-tests
> ### End-to-End Integration tests
> [...]
> Install the necessary puppeteer-related Javascript packages:
> `$ npm install --no-save jest jest-puppeteer puppeteer`

**Pull request merged**
