### PR TITLE
adding main

### PR DESCRIPTION
**Pull request by h4ck3rm1k3**

### CODE REVIEW

**Comment by posativ** [comment]
The `setup.py` already provides an entrypoint to main.

**Comment by h4ck3rm1k3** [comment]
yes, but I wanted to be able to run it without installing it or or running setup.py

**Comment by posativ** [comment]
Does it still work with `pkg_resources` then?

**Comment by h4ck3rm1k3** [comment]
It should not affect anything, it is just an addon and a common practice.

On Wed, Mar 30, 2016 at 3:09 AM, Martin Zimmermann <notifications@github.com
> wrote:

> Does it still work with pkg_resources then?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/posativ/isso/pull/246#issuecomment-203283141>
>



-- 
James Michael DuPont
Kansas Linux Fest http://kansaslinuxfest.us
Free/Libre Open Source and Open Knowledge Association of Kansas
http://openkansas.us
Member of Free Libre Open Source Software Kosova http://www.flossk.org
Saving Wikipedia(tm) articles from deletion http://SpeedyDeletion.wikia.com

**Comment by posativ** [comment]
This change is not useful, let me show why.

```diff
diff --git a/isso/__init__.py b/isso/__init__.py
index ff8f6b4..99a4ec1 100644
--- a/isso/__init__.py
+++ b/isso/__init__.py
@@ -268,3 +268,6 @@ def main():
             if ex.errno != errno.ENOENT:
                 raise
         wsgi.SocketHTTPServer(sock, make_app(conf)).serve_forever()
+
+if __name__ == '__main__':
+    main()
```

Now, you can just execute `__init__.py`, e .g. `python isso/__init__.py`, which results into a `DistributionNotFound` error. You have to use `python setup.py develop` (only symlinks) or `python setup.py install`.

```python
Traceback (most recent call last):
  File "isso/__init__.py", line 31, in <module>
    dist = pkg_resources.get_distribution("isso")
  File "/home/user/.local/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 540, in get_distribution
    dist = get_provider(dist)
  File "/home/user/.local/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 420, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/user/.local/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 941, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/user/.local/lib64/python3.4/site-packages/pkg_resources/__init__.py", line 828, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'isso' distribution was not found and is required by the application
```

**Pull request closed without merging**
