### PR TITLE
Configurable nesting limit

### LINKED ISSUE #210: Make comment nesting level configurable
The current Isso JavaScript client allows for only one level of comment nesting. While this may be a good UX choice for most, there are many situations where arbitrary levels of comment nesting are desired.

The Isso client should support a user-configurable nesting level limit. The default should be "1", or the same limit as currently imposed, for backwards compatibility.

### PR DESCRIPTION
**Pull request by sprin**
Resolves #210

### CODE REVIEW

**Comment by pozitron57** [comment]
Let me clarify, does it allow to set any nesting level (including 0 = nesting disabled)?

**Comment by sprin** [comment]
Yes, that's correct, nesting is disabled when `nesting-level` is 0, and only top-level comments will be displayed. In this case, the "reply" links on top-level comments should probably not be shown. I will add this.

**Comment by pozitron57** [comment]
OK, nice! For `nesting-level = 0` maybe it is better that button `reply` will paste the text of the commenter to the comment form  with comment with `>` prefix? [Juvia](http://juvia-demo.phusion.nl/admin/sites/1/test) (login `discard@phusion.nl`, pass `123456`) does it. If you click `reply to this comment`, you 'll have this in your comment form:

    *Nickname wrote*:
    > text of the comment.

But Isso doesn't show preview on-the-fly and for anyone who isn't familiar with markdown syntax it might be a bit confusing.

**Comment by sprin** [comment]
> OK, nice! For nesting-level = 0 maybe it is better that button reply will paste the text of the commenter to the comment form with comment with > prefix?

I think this is fairly common behavior with single-threaded discussion/comment systems, but I think it should be implemented in a another PR as separate option, eg. "quoted-replies".

I think this PR is ready to be considered for merge. The failing check is related to the installed misaka version, which is resolved by either #212 or #214.

**Comment by ix5** [comment]
See https://github.com/posativ/isso/issues/210#issuecomment-1001245602 and https://github.com/posativ/isso/issues/79

Maybe opinions on this have changed, but allowing more nesting levels would also require a server-side change.

**Comment by ix5** [comment]
Nesting will continue to be limited to one level deep.

**Pull request closed without merging**
