### PR TITLE
css, js: Prefix all directives with 'isso-'

### PR DESCRIPTION
**Pull request by ix5**
This "namespaces" Isso's CSS in order not to conflict with things on page

Fixes https://github.com/posativ/isso/issues/442

### CODE REVIEW

**Comment by ix5** [comment]
Also, while I have your attention: @Kerumen @adroste

**Comment by adroste** [comment]
@ix5 This is definitely a breaking change regarding custom overrides. So anything below v0.13 could lead to mad users.

**Comment by ix5** [comment]
Would you mind going over the change and testing whether I missed anything or fat-fingered some string?

**Comment by adroste** [comment]
Looks good (without testing it locally).

At first I thought you missed the input form selectors, but they are limited by the postbox scope.

https://github.com/posativ/isso/blob/88653210660af2069329896f8fb05d603b9881f4/isso/js/app/isso.js#L88-L91

Nevertheless, you could also prefix the keys for the items that are persisted in the localstorage:

https://github.com/posativ/isso/blob/88653210660af2069329896f8fb05d603b9881f4/isso/js/app/isso.js#L122-L124

**Comment by ix5** [comment]
> Nevertheless, you could also prefix the keys for the items that are persisted in the localstorage:
> 
> https://github.com/posativ/isso/blob/88653210660af2069329896f8fb05d603b9881f4/isso/js/app/isso.js#L122-L124

That's a great catch, thank you! Moving to prefixed key names will ofc invalidate any username/email/website users have set, but imo it's not worth to write a migration for that.

(Note that I hope you just happened to review the version I pushed after I rebased it on https://github.com/posativ/isso/pull/822 ;-)

**Pull request merged**
